### ISSUE TITLE
Crear el fichero .csv donde se almacenan los pares (kindCode,kind)

### ISSUE THREAD

**Issue by CarlosSanabriaM** [Arquisoft/Agents_e5b#7]

**Comment by adrycarou896** [comment]
Creado el fichero csv (src/main/resources/kinds.xlsx) y Reader del mismo hecho, se cerrará esta incidencia cuando todas las demás partes estén listas y todo funcione correctamente.

**Comment by CarlosSanabriaM** [comment]
Cambiado el fichero (src/main/resources/kinds.xlsx) por (src/main/resources/kinds.csv).
Lector del csv terminado y operativo.
