### ISSUE TITLE
Corregir los errores del código JPA del proyecto base

### ISSUE THREAD

**Issue by CarlosSanabriaM** [Arquisoft/Agents_e5b#8]

**Comment by adrycarou896** [comment]
En principio está completado, aunque hay que esperar a finalizar el resto de puntos de la adaptación para comprobar que el JPA funciona correctamente y cerrar esta incidencia.

**Comment by CarlosSanabriaM** [comment]
El entityManager se crea dentro de la clase DataBaseConfig.
La consulta parece que no puede llevar select porque si no no funciona.
Falta comprobar si el updateInfo se puede hacer sin recurrir al dummyAgent, y por tanto, puede ser eliminado.

**Comment by adrycarou896** [comment]
Arreglado el updateIndo
