### ISSUE TITLE
Comprobar la función que tiene la clase AgentMin y borrarla si no tiene ninguna

### ISSUE THREAD

**Issue by CarlosSanabriaM** [Arquisoft/Agents_e5b#9]
La clase AgentMin (antes llamada CitizenMin), creo que no es utilizada en ningún sitio de la aplicación, salvo en una clase de test (y se utiliza para comprobar que funcionan los gets y sets, lo cual no tiene mucho sentido).

Creo que no tiene ningún tipo de utilidad y debería borrarse.

**Comment by adrycarou896** [comment]
Aunque no sea relevante para la funcionalidad de la aplicación, si que puede ser útil para realizar pruebas, así que como queráis, yo por mí no la eliminaba, aunque si consideráis que es totalmente innecesaria se elimina.

**Comment by RosaValdesPire** [comment]
yo opino que de momento deberíamos dejarla

**Comment by CarlosSanabriaM** [comment]
Al final sí que hace falta, para pasar datos

**Comment by CarlosSanabriaM** [comment]
Parece que sí que es importante dicha clase, ya que actua como un Dto, pasando datos entre capas. 
Es el valor de retorno del metodo getAgentInfo.
Debemos mantener dicha clase.
